CREATE TABLE `tsc`.`msgboard_topics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_by` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

CREATE TABLE `tsc`.`msgboard_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `content` LONGTEXT NOT NULL,
  `date_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_by` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));
